services:
  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"  # For client connections
    environment:
      - KAFKA_KRAFT_MODE=yes
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      - ALLOW_PLAINTEXT_LISTENER=yes
    networks:
      - iris-net

  create-topic:
    image: bitnami/kafka:latest
    depends_on:
      - kafka
    entrypoint: ["/bin/bash", "/app/create-topic.sh"]
    volumes:
      - ./kafka/init/create_topic.sh:/app/create-topic.sh
    networks:
      - iris-net

networks:
  iris-net:
    driver: bridge
    external: true